locale                   : "en-US"
site_theme               : "default"
title                    : "Simran Koul - Environmental Science & Air Pollution Researcher"
title_separator          : "-"
name                     : &name "Simran Koul"
description              : &description "PhD Student | Air Pollution, Geospatial Analysis, & Data Science | UCSB Bren School"
url                      : https://simkoul.github.io
baseurl                  : ""
repository               : "simkoul/simkoul.github.io"

author:
  avatar           : "profile.png"
  name             : "Simran Koul"
  pronouns         : "she/her"  
  bio              : "PhD Student at UCSB Bren School, focusing on air pollution, PM2.5, geospatial analysis, and social inequities."
  location         : "Santa Barbara, CA"
  employer         : "University of California, Santa Barbara (UCSB)"
  uri              : "https://www.bren.ucsb.edu"
  email            : "simran.koul@ucsb.edu" 

  # Academic websites
  arxiv            : "https://arxiv.org/search/?query=Simran+Koul&searchtype=all" # If applicable
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : "https://impactstory.org/u/Simran-Koul" # If applicable
  orcid            : "https://orcid.org/0000-0000-0000-0000" # Update with actual ORCID
  semantic         : "https://www.semanticscholar.org/author/Simran-Koul" # If applicable
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=simran+koul" # If applicable
  researchgate     : "https://www.researchgate.net/profile/Simran-Koul"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=000000000000" # Update if available

  # Repositories and software development
  bitbucket        : "simrankoul"
  codepen          : "simrankoul"
  dribbble         : "simrankoul"
  github           : "simkoul"
  kaggle           : "simrankoul" # If applicable
  stackoverflow    : "1234567/simran-koul" # Update with correct ID if needed

  # Social media
  bluesky          : "bsky.app/simrankoul"
  facebook         : "simrankoul"
  flickr           : ""
  foursquare       : ""
  goodreads        : ""
  google_plus      : ""
  keybase          : ""
  instagram        : "skoul_research"
  lastfm           : ""
  linkedin         : "https://www.linkedin.com/in/simran-koul-ucsb"
  mastodon         : "https://mastodon.social/@simrankoul"
  medium           : "https://medium.com/@simrankoul"
  pinterest        : ""
  soundcloud       : ""
  steam            : ""
  telegram         : ""
  tumblr           : ""
  twitter          : "simrankoul_"
  vine             : ""
  weibo            : ""
  wikipedia        : ""
  xing             : ""
  youtube          : "https://www.youtube.com/@simrankoul"
  zhihu            : ""

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

teaser                   : "banner.png"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : "false"

staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"

google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-000000-2" # Update with actual tracking ID

sass:
  sass_dir: _sass
  style: compressed 

permalink: /:categories/:title/
timezone: America/Los_Angeles



# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
