# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Simran Koul - Environmental Science Researcher"
title_separator          : "-"
name                     : &name "Simran Koul"
description              : &description "PhD Student | Environmental Science & Air Pollution Research | Geospatial & Data Analysis"
url                      : https://simkoul.github.io
baseurl                  : ""
repository               : "simkoul/simkoul.github.io"

author:
  avatar           : "profile.png"
  name             : "Simran Koul"
  pronouns         : "she/her"  
  bio              : "PhD Student at UCSB Bren School, focusing on Environmental Science, PM2.5 pollution, and geospatial analysis."
  location         : "Santa Barbara, CA"
  employer         : "University of California, Santa Barbara (UCSB)"
  uri              : "https://www.bren.ucsb.edu"
  email            : "simran.koul@ucsb.edu" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "https://orcid.org/0000-0000-0000-0000" # Update with actual ORCID
  researchgate     : "https://www.researchgate.net/profile/Simran-Koul"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=000000000000" # Update if available

  # Repositories and software development
  github           : "simkoul"
  kaggle           : "simkoul" # If applicable
  stackoverflow    : "1234567/simran-koul" # Update with correct ID if needed

  # Social media
  linkedin         : "https://www.linkedin.com/in/simran-koul-ucsb"
  twitter          : "simrankoul_" # If you want to use Twitter/X
  instagram        : "skoul_research" # If you decide to use IG for research content
  bluesky          : "bsky.app/simrankoul" # If applicable

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

teaser                   : "banner.png"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : "false"

analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-000000-2" # Update with actual tracking ID

sass:
  sass_dir: _sass
  style: compressed 
locale                   : "en-US"
site_theme               : "default"
title                    : "Simran Koul - Environmental Science Researcher"
title_separator          : "-"
name                     : &name "Simran Koul"
description              : &description "PhD Student | Environmental Science & Air Pollution Research | Geospatial & Data Analysis"
url                      : https://simkoul.github.io
baseurl                  : ""
repository               : "simkoul/simkoul.github.io"

author:
  avatar           : "profile.png"
  name             : "Simran Koul"
  pronouns         : "she/her"  
  bio              : "PhD Student at UCSB Bren School, focusing on Environmental Science, PM2.5 pollution, and geospatial analysis."
  location         : "Santa Barbara, CA"
  employer         : "University of California, Santa Barbara (UCSB)"
  uri              : "https://www.bren.ucsb.edu"
  email            : "simran.koul@ucsb.edu" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "https://orcid.org/0000-0000-0000-0000" # Update with actual ORCID
  researchgate     : "https://www.researchgate.net/profile/Simran-Koul"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=000000000000" # Update if available

  # Repositories and software development
  github           : "simkoul"
  kaggle           : "simkoul" # If applicable
  stackoverflow    : "1234567/simran-koul" # Update with correct ID if needed

  # Social media
  linkedin         : "https://www.linkedin.com/in/simran-koul-ucsb"
  twitter          : "simrankoul_" # If you want to use Twitter/X
  instagram        : "skoul_research" # If you decide to use IG for research content
  bluesky          : "bsky.app/simrankoul" # If applicable

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

teaser                   : "banner.png"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : "false"

analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-000000-2" # Update with actual tracking ID

sass:
  sass_dir: _sass
  style: compressed 

permalink: /:categories/:title/
timezone: America/Los_Angeles
